<script>
  import { ApiError, deleteExpense, getExpenses, updateClassification, enrichAccount, saveBudget, deleteBudget, logout } from './lib/api.js';
  import SectionState from './SectionState.svelte';
  export let sections; export let taxonomy; export let taxonomyError; export let selectedMonth; export let filters; export let destination; export let onMonthChange; export let onFiltersChange; export let refreshSummary; export let refreshExpenses; export let refreshAccounts; export let refreshEnrichment; export let refreshBudgets; export let onExpired; export let onLogout;
  let items = []; let loadedPage = null; let nextBeforeId = null; let loadingMore = false; let editing = null; let accountEditing = null; let saving = false; let formError = ''; let toast = ''; let budgetCategory = ''; let budgetAmount = ''; let loggingOut = false;
  let category = ''; let subcategory = ''; let accountForm = {};
  $: summary = sections.summary.data || {}; $: insight = sections.insights.data || {}; $: accounts = Array.isArray(sections.accounts.data) ? sections.accounts.data : sections.accounts.data?.items || []; $: budgets = (Array.isArray(sections.budgets.data) ? sections.budgets.data : sections.budgets.data?.items || []).filter(x => x.active !== false).sort((a,b) => a.category.localeCompare(b.category)); $: enrichment = sections.enrichment.data || { hasItems:false, count:0, items:[] };
  $: expensePage = sections.expenses.data; $: if (expensePage && expensePage !== loadedPage) { loadedPage = expensePage; items = expensePage.items || expensePage.expenses || []; nextBeforeId = expensePage.nextBeforeId ?? null; }
  $: categories = insight?.summary?.categories || insight?.categories || insight?.categoryBreakdown || []; $: normalizedCategories = Array.isArray(categories) ? categories : Object.entries(categories).map(([name, amount]) => ({ name, amount }));
  $: categoryOptions = taxonomy?.categories || []; $: selectedCategory = categoryOptions.find(x => x.name.toLowerCase() === category.trim().toLowerCase()); $: subcategoryOptions = selectedCategory?.subcategories || []; $: validClassification = !!selectedCategory && subcategoryOptions.some(x => x.toLowerCase() === subcategory.trim().toLowerCase());
  $: activeAccount = accounts.find(x => x.id === filters.accountId); $: activeFilterLabels = [activeAccount?.name, filters.category, filters.subcategory].filter(Boolean); $: filterSummary = expensePage?.filterSummary || null;
  $: if (destination.startsWith('/portal/accounts/') && accounts.length && !accountEditing) { const id = Number(destination.split('/').pop()); const found = accounts.find(x => x.id === id); if (found) openAccount(found); }
  $: if (destination.startsWith('/portal/expenses/') && items.length && !editing) { const id = Number(destination.split('/').pop()); const found = items.find(x => x.id === id); if (found) openEdit(found); }
  $: currency = summary?.currency || insight?.currency || 'INR';
  const money = (value, code) => new Intl.NumberFormat(undefined, { style:'currency', currency:code || currency || 'INR', maximumFractionDigits:0 }).format(Number(value || 0));
  function monthLabel(value) { const [y,m] = value.split('-').map(Number); return new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric'}).format(new Date(y,m-1)); }
  const message = x => x.originalMessage || x.message || x.description || 'Expense'; const expenseCategory = x => x.category?.name || x.category || 'Uncategorised'; const expenseSubcategory = x => x.subcategory?.name || x.subcategory || 'General'; const source = x => x.sourceAccount?.name || x.sourceAccount || x.account?.name || x.account || 'Payment source not recorded';
  const dateLabel = value => value ? new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(value)) : '';
  const humanField = value => ({sourceAccount:'Payment source',category:'Category',subcategory:'Subcategory',accountBalanceImpact:'Account balance',currentBalance:'Current balance',creditLimit:'Credit limit',billingDay:'Bill generation day',dueDay:'Payment due day'}[value] || value);
  const categoryName = item => item.name || item.category || 'Other'; const subcategoriesFor = item => item.subcategories || item.subcategoryBreakdown || []; const subcategoryName = item => typeof item === 'string' ? item : item.name || item.subcategory;
  function dashboardUrl() { const params = new URLSearchParams({ month: selectedMonth }); if (filters.accountId) params.set('accountId', filters.accountId); if (filters.category) params.set('category', filters.category); if (filters.subcategory) params.set('subcategory', filters.subcategory); return `/dashboard?${params}`; }
  function setFilter(patch) { onFiltersChange({ ...filters, ...patch }); } function clearFilters() { onFiltersChange({ month: selectedMonth }); }
  function reviewEnrichment(item) {
    history.pushState({}, '', item.portalPath);
    if (item.type === 'ACCOUNT') {
      const match = accounts.find(account => account.id === item.id);
      if (match) openAccount(match); else { history.replaceState({}, '', dashboardUrl()); formError = 'This account is no longer available. Refresh the accounts section and try again.'; }
      return;
    }
    const match = items.find(expense => expense.id === item.id);
    if (match) openEdit(match); else { history.replaceState({}, '', dashboardUrl()); formError = 'This transaction is not in the current expense page. Complete transaction enrichment is not supported by the current API yet.'; }
  }
  function closeExpenseEditor() { editing = null; history.replaceState({}, '', dashboardUrl()); }
  function closeAccountEditor() { accountEditing = null; history.replaceState({}, '', dashboardUrl()); }
  function showToast(text) { toast=text; setTimeout(()=>toast='',2600); } function handleError(cause,fallback) { if (cause instanceof ApiError && cause.status===401) onExpired(); else formError=cause?.message || fallback; }
  async function loadMore() { if (loadingMore || nextBeforeId==null) return; loadingMore=true; try { const page=await getExpenses(filters,nextBeforeId,20); items=[...items,...(page.items||page.expenses||[])]; nextBeforeId=page.nextBeforeId??null; } catch(c){handleError(c,'Could not load more expenses.')} finally{loadingMore=false;} }
  function openEdit(item){ editing=item; category=expenseCategory(item); subcategory=expenseSubcategory(item); formError=''; }
  async function saveEdit(){ if(!validClassification||saving)return; saving=true; formError=''; try{await updateClassification(editing.id,selectedCategory.name,subcategory,editing.version); editing=null; history.replaceState({},'',dashboardUrl()); await Promise.all([refreshExpenses(),refreshSummary(),refreshEnrichment()]); showToast('Expense updated');}catch(c){handleError(c,'Could not update expense.')}finally{saving=false;} }
  async function removeExpense(item){ if(!confirm('Delete this expense? This cannot be undone.'))return; try{await deleteExpense(item.id,item.version); await Promise.all([refreshExpenses(),refreshSummary(),refreshEnrichment()]); showToast('Expense deleted');}catch(c){handleError(c,'Could not delete expense.')} }
  function openAccount(item){accountEditing=item;accountForm={currentBalance:item.currentBalance??'',creditLimit:item.creditLimit??'',billingDay:item.billingDay??'',dueDay:item.dueDay??''};formError='';}
  async function saveAccount(){ const changes={}; for(const key of ['currentBalance','creditLimit','billingDay','dueDay']){const value=accountForm[key];if(value!==''&&Number(value)!==Number(accountEditing[key]))changes[key]=Number(value);} if(changes.currentBalance<0){formError='Current balance cannot be negative.';return;} if('creditLimit'in changes&&changes.creditLimit<=0){formError='Credit limit must be greater than zero.';return;} for(const key of ['billingDay','dueDay'])if(key in changes&&(!Number.isInteger(changes[key])||changes[key]<1||changes[key]>31)){formError='Billing and due days must be whole numbers from 1 to 31.';return;} if(!Object.keys(changes).length)return; saving=true;formError='';try{await enrichAccount(accountEditing.id,changes);accountEditing=null;history.replaceState({},'',dashboardUrl());await Promise.all([refreshAccounts(),refreshEnrichment()]);showToast('Account details saved');}catch(c){handleError(c,'Could not save account details.')}finally{saving=false;} }
  async function submitBudget(){ const amount=Number(budgetAmount);if(!budgetCategory.trim()||amount<=0){formError='Enter a category and a positive monthly amount.';return;}saving=true;formError='';try{await saveBudget(budgetCategory.trim(),amount);budgetCategory='';budgetAmount='';await refreshBudgets();showToast('Budget saved');}catch(c){handleError(c,'Could not save budget.')}finally{saving=false;} }
  async function removeBudget(item){if(!confirm(`Deactivate the ${item.category} budget?`))return;try{await deleteBudget(item.id);await refreshBudgets();showToast('Budget deactivated');}catch(c){handleError(c,'Could not deactivate budget.')} }
  async function signOut(){loggingOut=true;try{await logout();onLogout();}catch(c){loggingOut=false;formError='Could not sign out.';}}
</script>
<header class="topbar"><a class="brand" href="/"><span class="logo">₹</span><span>Expense AI</span></a><div class="topbar-actions"><label class="month-picker"><span>Month</span><input aria-label="Select dashboard month" type="month" value={selectedMonth} on:change={e=>onMonthChange(e.currentTarget.value)}/></label><button class="logout-button" on:click={signOut} disabled={loggingOut}>Sign out</button></div></header>
<main class="dashboard-shell">
  <section class="welcome"><div><p class="eyebrow">Your spending</p><h1>{monthLabel(selectedMonth)}</h1><p>A clear view of your money, with details captured on WhatsApp.</p></div><div class="secure-pill"><span></span>Private & secure</div></section>
  {#if formError}<div class="notice error" role="alert"><span>{formError}</span><button on:click={()=>formError=''} aria-label="Dismiss">×</button></div>{/if}
  <section class="metric-grid" aria-label="Monthly summary">
    {#if sections.summary.status==='loading'}{#each [1,2] as _}<div class="metric skeleton"><i></i><b></b><span></span></div>{/each}
    {:else if sections.summary.status==='error'}<article class="panel section-error" role="alert"><h2>Summary unavailable</h2><p>{sections.summary.error}</p><button class="secondary" on:click={refreshSummary}>Try again</button></article>
    {:else}<article class="metric accent"><p>Total spent</p><strong>{money(summary.totalSpend)}</strong><span>{monthLabel(summary.month||selectedMonth)}</span></article><article class="metric"><p>Transactions</p><strong>{summary.transactionCount||0}</strong><span>Recorded expenses</span></article>{/if}
  </section>
  <SectionState section={sections.enrichment} title="Needs enrichment" retry={refreshEnrichment}>
    {#if enrichment.hasItems}<article class="panel enrichment-panel"><div class="panel-heading"><div><p class="eyebrow">Needs enrichment</p><h2><span aria-label="Attention">⚠</span> {enrichment.count} pending {enrichment.count===1?'item':'items'}</h2></div></div><div class="enrichment-list">{#each enrichment.items||[] as item}<button type="button" on:click={()=>reviewEnrichment(item)} class="enrichment-item"><div><b>{item.type==='ACCOUNT'?'Account':'Transaction'}</b><strong>{item.description}</strong><small>{(item.missingFields||[]).map(humanField).join(' · ')}</small></div><span>Review →</span></button>{/each}</div></article>{/if}
  </SectionState>
  <SectionState section={sections.accounts} title="Accounts" retry={refreshAccounts}><article class="panel full-panel"><div class="panel-heading"><div><p class="eyebrow">Money sources</p><h2>Accounts</h2></div><span>{accounts.length}</span></div>{#if accounts.length}<div class="account-grid">{#each accounts as item}<div class:active-filter={filters.accountId===item.id} class="account-card"><button class="account-filter-main" on:click={()=>setFilter({accountId:filters.accountId===item.id?undefined:item.id})} aria-pressed={filters.accountId===item.id}><span><b>{item.name}</b><small>{item.type?.replaceAll('_',' ')}</small></span><strong>{item.primaryValue==null?'Details needed':money(item.primaryValue,item.currency||currency)}</strong><small>{item.primaryLabel}{item.lastActivityAt?` · ${dateLabel(item.lastActivityAt)}`:''}</small>{#if item.overLimit}<em>Over limit by {money(item.overLimitAmount,item.currency||currency)}</em>{/if}</button><button class="account-manage" on:click={()=>openAccount(item)}>Manage details</button></div>{/each}</div>{:else}<p class="empty-copy">No accounts are available yet. New account creation is not supported in the portal yet.</p>{/if}</article></SectionState>
  <section class="content-grid">
    <SectionState section={sections.insights} title="Spending insights" retry={()=>location.reload()}><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Insights</p><h2>Spending by category</h2></div></div>{#if normalizedCategories.length}<div class="category-list">{#each normalizedCategories as item}<div class:active-category={filters.category===categoryName(item)} class="category-row"><button class="category-filter" on:click={()=>setFilter({category:filters.category===categoryName(item)?undefined:categoryName(item),subcategory:undefined})} aria-pressed={filters.category===categoryName(item)}><div class="category-line"><span>{categoryName(item)}</span><strong>{money(item.amount||item.total)}</strong></div></button>{#if filters.category===categoryName(item)&&subcategoriesFor(item).length}<div class="subcategory-list">{#each subcategoriesFor(item) as child}<button class:active-filter={filters.subcategory===subcategoryName(child)} on:click={()=>setFilter({category:categoryName(item),subcategory:filters.subcategory===subcategoryName(child)?undefined:subcategoryName(child)})} aria-pressed={filters.subcategory===subcategoryName(child)}><span>{subcategoryName(child)}</span><strong>{money(child.amount||child.total)}</strong></button>{/each}</div>{/if}</div>{/each}</div>{:else}<p class="empty-copy">No category insights for this month.</p>{/if}</article></SectionState>
    <SectionState section={sections.expenses} title="Recent expenses" retry={refreshExpenses}><article class="panel"><div class="panel-heading"><div><p class="eyebrow">Activity</p><h2>{activeFilterLabels.length?'Filtered expenses':'Recent expenses'}</h2></div><span class:filter-active={activeFilterLabels.length}>{filterSummary&&activeFilterLabels.length?`${filterSummary.transactionCount} transactions · ${money(filterSummary.totalAmount)}`:'Latest first'}</span></div>{#if activeFilterLabels.length}<div class="filter-chips">{#if activeAccount}<button on:click={()=>setFilter({accountId:undefined})}>{activeAccount.name} <span>×</span></button>{/if}{#if filters.category}<button on:click={()=>setFilter({category:undefined,subcategory:undefined})}>{filters.category} <span>×</span></button>{/if}{#if filters.subcategory}<button on:click={()=>setFilter({subcategory:undefined})}>{filters.subcategory} <span>×</span></button>{/if}<button class="clear-filters" on:click={clearFilters}>Clear all</button></div>{/if}{#if items.length}<div class="expense-list">{#each items as item}<article class="expense-item"><div class="expense-top"><strong>{money(item.amount)}</strong><time>{dateLabel(item.transactionTime||item.date||item.createdAt)}</time></div><p class="message">“{message(item)}”</p><div class="expense-meta"><div><b>{expenseCategory(item)} <span>›</span> {expenseSubcategory(item)}</b><small>{item.merchant?`${item.merchant} · `:''}{source(item)}</small></div>{#if item.needsReview}<span class="review" aria-label="Needs review">⚠ Needs review</span>{/if}</div><div class="expense-actions"><button class="text-button" on:click={()=>openEdit(item)}>Edit category</button><button class="text-button delete" on:click={()=>removeExpense(item)}>Delete</button></div></article>{/each}</div>{#if nextBeforeId!=null}<button class="load-more" on:click={loadMore} disabled={loadingMore}>{loadingMore?'Loading…':'Load more'}</button>{/if}{:else}<p class="empty-copy">No expenses match the selected filters.</p>{/if}</article></SectionState>
  </section>
  <SectionState section={sections.budgets} title="Budgets" retry={refreshBudgets}><article class="panel full-panel"><div class="panel-heading"><div><p class="eyebrow">Plan ahead</p><h2>Monthly budgets</h2></div><span>{budgets.length} active</span></div><p class="section-intro">WhatsApp alerts will continue when spending approaches or exceeds a budget.</p><form class="budget-form" on:submit|preventDefault={submitBudget}><label>Category<input bind:value={budgetCategory} placeholder="e.g. Food" required/></label><label>Monthly limit<input bind:value={budgetAmount} type="number" min="0.01" step="0.01" placeholder="₹ 12,000" required/></label><button class="primary" disabled={saving}>Save budget</button></form>{#if budgets.length}<div class="budget-list">{#each budgets as item}<div><span><b>{item.category}</b><small>{money(item.monthlyLimit)} per month</small></span><button on:click={()=>{budgetCategory=item.category;budgetAmount=item.monthlyLimit}}>Edit</button><button class="delete" on:click={()=>removeBudget(item)}>Deactivate</button></div>{/each}</div>{:else}<p class="empty-copy">No active budgets. Add one above to start receiving alerts.</p>{/if}</article></SectionState>
</main>
{#if editing}<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><button class="close" on:click={closeExpenseEditor} aria-label="Close">×</button><p class="eyebrow">Transaction</p><h2>Edit classification</h2><div class="original"><small>Original message</small><p>“{message(editing)}”</p></div>{#if editing.needsEnrichment}<p class="info-note">Payment-source and balance enrichment are not supported by the current API yet. You can update classification here.</p>{/if}<label>Category<input list="categories" bind:value={category}/><datalist id="categories">{#each categoryOptions as x}<option value={x.name}></option>{/each}</datalist></label><label>Subcategory<input list="subcategories" bind:value={subcategory}/><datalist id="subcategories">{#each subcategoryOptions as x}<option value={x}></option>{/each}</datalist></label>{#if taxonomyError}<p class="form-error">{taxonomyError}</p>{/if}<div class="modal-actions"><button class="secondary" on:click={closeExpenseEditor}>Cancel</button><button class="primary" on:click={saveEdit} disabled={!validClassification||saving}>Save changes</button></div></div></div>{/if}
{#if accountEditing}<div class="modal-backdrop"><div class="modal" role="dialog" aria-modal="true"><button class="close" on:click={closeAccountEditor} aria-label="Close">×</button><p class="eyebrow">Account details</p><h2>{accountEditing.name}</h2><label>Current balance<input type="number" min="0" bind:value={accountForm.currentBalance}/></label>{#if accountEditing.type==='CREDIT_CARD'}<label>Credit limit<input type="number" min="0.01" bind:value={accountForm.creditLimit}/></label><label>Bill generation day<input type="number" min="1" max="31" step="1" bind:value={accountForm.billingDay}/></label><label>Payment due day<input type="number" min="1" max="31" step="1" bind:value={accountForm.dueDay}/></label>{/if}<div class="modal-actions"><button class="secondary" on:click={closeAccountEditor}>Cancel</button><button class="primary" on:click={saveAccount} disabled={saving}>Save details</button></div></div></div>{/if}
{#if toast}<div class="toast" role="status">✓ {toast}</div>{/if}
