<script>
  import { ApiError, createMissingDateContext, logout } from './lib/api.js';
  import SectionState from './SectionState.svelte';
  export let calendarSection; export let recentSection; export let storiesSection; export let selectedMonth; export let onMonthChange; export let refreshCalendar; export let refreshRecent; export let refreshStories; export let onLogout;
  let selectedDay = null, loggingOut = false, signOutError = '', receiptIndex = 0, openedStory = null, addingContext = false, addError = '', handoff = null;
  $: data = calendarSection.data || {}; $: currency = data.currency || 'INR'; $: calendar = buildCalendar(selectedMonth, data.days || []); $: selected = selectedDay == null ? null : calendar.days.find(day => day.day === selectedDay); $: recentData = recentSection.data || {}; $: recentTransactions = recentData.items || recentData.expenses || []; $: recent = recentTransactions[receiptIndex] || null; $: storyData = storiesSection.data || {}; $: stories = storyData.stories || storyData.moneyStories || storyData.storyCards || [];
  const money = value => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value || 0));
  function monthName(value) { const [year, month] = value.split('-').map(Number); return new Intl.DateTimeFormat(undefined, { month: 'long' }).format(new Date(year, month - 1)); }
  function monthLabel(value) { const [year, month] = value.split('-').map(Number); return new Intl.DateTimeFormat(undefined, { month: 'long', year: 'numeric' }).format(new Date(year, month - 1)); }
  function greeting() { const hour = new Date().getHours(); return hour < 12 ? 'Good morning' : hour < 17 ? 'Good afternoon' : 'Good evening'; }
  function dateLabel(value) { return value ? new Intl.DateTimeFormat(undefined, { day: 'numeric', month: 'short' }).format(new Date(value)) : ''; }
  function moveReceipt(offset) { if (recentTransactions.length) receiptIndex = (receiptIndex + offset + recentTransactions.length) % recentTransactions.length; }
  function changeMonth(offset) { const [year, month] = selectedMonth.split('-').map(Number); const next = new Date(year, month - 1 + offset).toISOString().slice(0, 7); if (next <= new Date().toISOString().slice(0, 7)) { selectedDay = null; onMonthChange(next); } }
  function buildCalendar(monthValue, apiDays) { const [year, month] = monthValue.split('-').map(Number), count = new Date(year, month, 0).getDate(), leading = (new Date(year, month - 1, 1).getDay() + 6) % 7, values = new Map(apiDays.map(item => [Number(String(item.date).slice(-2)), item])), today = new Date(), isCurrent = today.getFullYear() === year && today.getMonth() + 1 === month; return { leading, days: Array.from({ length: count }, (_, index) => { const day = index + 1, value = values.get(day) || {}; return { day, totalSpend: Number(value.totalSpend || 0), transactionCount: Number(value.transactionCount || 0), intensity: Math.max(0, Math.min(4, Number(value.intensity || 0))), future: isCurrent && day > today.getDate() }; }) }; }
  async function addMissingDate() { if (!selected || addingContext) return; addingContext = true; addError = ''; const date = `${selectedMonth}-${String(selected.day).padStart(2, '0')}`; try { const result = await createMissingDateContext(date, data.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone); handoff = { ...result, date }; } catch (cause) { addError = cause instanceof ApiError ? cause.message : 'Could not prepare WhatsApp recording. Please try again.'; } finally { addingContext = false; } }
  async function signOut() { loggingOut = true; signOutError = ''; try { await logout(); onLogout(); } catch { loggingOut = false; signOutError = 'Could not sign out. Please try again.'; } }
</script>

<header class="portal-topbar"><a class="wordmark" href="/dashboard"><span>₹</span>Money Stories</a><label class="month-switcher"><button aria-label="Previous month" on:click={() => changeMonth(-1)}>←</button><input aria-label="Select month" type="month" value={selectedMonth} max={new Date().toISOString().slice(0, 7)} on:change={event => { selectedDay = null; receiptIndex = 0; openedStory = null; onMonthChange(event.currentTarget.value); }}/><button aria-label="Next month" on:click={() => changeMonth(1)}>→</button></label></header>
<main class="story-shell">
  {#if openedStory}
    <section class="story-detail"><button class="back-button" on:click={() => openedStory = null}>← Back to stories</button><p class="micro-label">{openedStory.type || 'MONEY STORY'} · {monthLabel(selectedMonth)}</p><h1>{openedStory.headline}</h1><div class="evidence-visual"><div><span>Observed amount</span><strong>{money(openedStory.amount)}</strong><i style={`width:${Math.min(100, Number(openedStory.impactPercent || 60))}%`}></i></div></div><p class="detail-copy">{openedStory.explanation}</p><div class="section-title"><h2>What caused it</h2><span>{openedStory.evidence?.length || 0} transactions</span></div><div class="evidence-list">{#each openedStory.evidence || [] as item}<div class="evidence-row"><div><strong>{item.merchant}</strong><span>{item.category} · {dateLabel(item.transactionDate)}</span></div><b>− {money(item.amount)}</b></div>{/each}</div><div class="context-card"><p class="micro-label">WHY THIS MATTERS</p><p>{openedStory.whyItMatters}</p></div></section>
  {:else}
  <section class="app-heading"><div><p class="micro-label">{monthName(selectedMonth).toUpperCase()}</p><h1>{greeting()}</h1><p>Your recorded spending, one day at a time.</p></div><button class="profile-button" on:click={signOut} disabled={loggingOut} aria-label="Sign out">{loggingOut ? '…' : 'D'}</button></section>
  {#if signOutError}<div class="notice error" role="alert"><span>{signOutError}</span><button on:click={() => signOutError = ''}>×</button></div>{/if}
  <SectionState section={calendarSection} title="Spending calendar" retry={refreshCalendar}>
    <section class="month-card"><div class="section-title"><div><p class="micro-label">MONTH AT A GLANCE</p><h2>{monthLabel(selectedMonth)}</h2></div><span>{data.recordedDays || 0} recorded days</span></div><div class="month-summary"><div><span>Total recorded</span><strong>{money(data.totalSpend)}</strong></div><div><span>Transactions</span><strong>{data.transactionCount || 0}</strong></div><div><span>Highest day</span><strong>{money(data.highestSpend)}</strong></div></div><div class="weekdays" aria-hidden="true">{#each ['Mon','Tue','Wed','Thu','Fri','Sat','Sun'] as day}<span>{day}</span>{/each}</div><div class="calendar">{#each Array(calendar.leading) as _}<span></span>{/each}{#each calendar.days as day}<button class:future={day.future} class:selected={selectedDay === day.day} class={`level-${day.intensity}`} disabled={day.future} on:click={() => { selectedDay = selectedDay === day.day ? null : day.day; addError = ''; }} aria-label={`${day.day} ${monthName(selectedMonth)}, ${day.transactionCount} transactions, ${money(day.totalSpend)}`}>{day.day}</button>{/each}</div><div class="legend"><span>Lower spend</span><div>{#each [0,1,2,3,4] as level}<i class={`level-${level}`}></i>{/each}</div><span>Higher spend</span></div>{#if selected}<div class="day-selection"><div><strong>{selected.day} {monthName(selectedMonth)}</strong><span>{selected.transactionCount} {selected.transactionCount === 1 ? 'transaction' : 'transactions'} · {money(selected.totalSpend)}</span><p>{selected.transactionCount ? 'Add another missing transaction for this date.' : 'No recorded transactions. Does anything look missing?'}</p></div><button on:click={addMissingDate} disabled={addingContext}>{addingContext ? 'Preparing…' : '＋ Add'}</button></div>{/if}{#if addError}<p class="form-error" role="alert">{addError}</p>{/if}</section>
    <SectionState section={recentSection} title="Recent transactions" retry={refreshRecent}>{#if recent}<section class="recent-block"><div class="recent-head"><div><p class="micro-label">RECENTLY CAPTURED</p><span>{receiptIndex + 1} of {recentTransactions.length}</span></div><div><button aria-label="Previous transaction" on:click={() => moveReceipt(-1)}>←</button><button aria-label="Next transaction" on:click={() => moveReceipt(1)}>→</button></div></div><div class="recent-transaction"><div><strong>{recent.merchant || recent.merchantName || recent.description || 'Expense'}</strong><span>{recent.category?.name || recent.category || 'Uncategorised'} · {recent.sourceAccount || 'Payment source not recorded'} · {dateLabel(recent.transactionDate || recent.transactionTime || recent.date)}</span></div><b>− {money(recent.amount)}</b></div></section>{/if}</SectionState>
    <SectionState section={storiesSection} title="Money Stories" retry={refreshStories}><section class="stories-section"><div class="section-title"><div><p class="micro-label">YOUR MONEY STORIES</p><h2>{stories.length ? 'Something changed' : 'Your financial story is forming'}</h2></div>{#if stories.length}<span>{stories.length} {stories.length === 1 ? 'story' : 'stories'}</span>{/if}</div>{#if stories.length}{#each stories as story, index}<button class:new-story={index === 0} class="story-card" on:click={() => openedStory = story}><span class="story-badge">{story.type || (index === 0 ? 'New pattern' : 'Story')}</span><div><h3>{story.headline}</h3><span>↗</span></div><p>{story.summary}</p><small>Tap to see the evidence →</small></button>{/each}{:else}<div class="empty-state story-empty"><span>✦</span><h2>No stories for this month yet.</h2><p>Stories appear only when there is enough trustworthy evidence—not after a fixed number of transactions.</p></div>{/if}</section></SectionState>
  </SectionState>
  {/if}
</main>
{#if handoff}<div class="modal-backdrop"><div class="modal whatsapp-handoff" role="dialog" aria-modal="true" aria-labelledby="whatsapp-title"><button class="close" aria-label="Close" on:click={() => handoff = null}>×</button><div class="auth-icon sent-icon" aria-hidden="true">✓</div><p class="micro-label">DATE READY</p><h2 id="whatsapp-title">Now continue in WhatsApp</h2><p>Send your missing transaction in WhatsApp. We’ll apply it to <strong>{dateLabel(`${handoff.date}T12:00:00`)}</strong>, even if you don’t mention the date again.</p><div class="security-note"><span aria-hidden="true">↗</span><p>This date context is temporary{handoff.expiresAt ? ` and expires at ${new Intl.DateTimeFormat(undefined, { hour: 'numeric', minute: '2-digit' }).format(new Date(handoff.expiresAt))}` : ''}.</p></div>{#if handoff.whatsappUrl}<a class="center-action whatsapp-action" href={handoff.whatsappUrl} target="_blank" rel="noopener">Open WhatsApp</a>{/if}<button class="auth-secondary" on:click={() => handoff = null}>Done</button></div></div>{/if}
